### ISSUE TITLE
 DB Types

### ISSUE THREAD

**Issue by skabashnyuk** [le0pard/pgtune#1]
Describe differences between DB Types in tooltip

**Comment by le0pard** [comment]
Why? It is already in selector.

**Comment by skabashnyuk** [comment]
I mean it is not very clear difference between "Online transaction system" and "Data warehouse" for instance. And it would be good to show definitions of each type in tooltip.

**Comment by le0pard** [comment]
"Data warehouse" - it is like Amazon Redshift, "Online transaction system" - like db for payment systems. Difference clear - it is different type of usage PostgreSQL.

**Comment by skabashnyuk** [comment]
Where I can find the definition of each type? In your meaning.

**Comment by le0pard** [comment]
https://en.wikipedia.org/wiki/Data_warehouse
https://en.wikipedia.org/wiki/Online_transaction_processing

It is not my meaning, it is standard definitions.
