### ISSUE TITLE
Remove: 9999 limit on MB

### ISSUE THREAD

**Issue by jmealo** [le0pard/pgtune#101]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could specify higher values in megabytes (or allow for decimal places in GB).

**Describe the solution you'd like**
To remove the 9999 limit on MB.

**Describe alternatives you've considered**
Forking.

**Additional context**
Kubernetes resource limits aren't going to have a clear boundary on GB, so MB is the best option.

**Comment by le0pard** [comment]
Hello. I dont get issue to select unit "MB", if you need "MB". Nobody will use "23846 MB", because in this case easy just switch to GB

<img width="870" alt="Screenshot 2024-11-27 at 23 13 50" src="https://github.com/user-attachments/assets/c678df72-e3a1-40e7-871e-911ad905f3e4">

**Comment by jmealo** [comment]
@le0pard: Thank you for the quick response.

- On physical hardware, your argument makes sense.
- On Docker/K8s/Cloud, you rarely have memory allocations that align to GB boundaries.

**Use case:**
- I need to enter things like 11328MB (see table below for why).
- Validation doesn't allow `11.328GB` (or any fractional units)
- There's no reason to have the arbitrary 9999 limitation -- removing it didn't break anything AFAICT.

These are some *real values* that I have to work with. For example, on Azure AKS:
```
 Node Memory (GB) | Node vCPU | PostgreSQL Memory Limit (Mi) | PostgreSQL CPU Limit (m) | Pooler Memory Limit (Mi) | Pooler CPU Limit (m) |
|-----------------:|----------:|-----------------------------:|-------------------------:|-------------------------:|---------------------:|
|                8 |         2 |                         6352 |                     1170 |                      128 |                  200 |
|               16 |         4 |                        13725 |                     2934 |                      128 |                  200 |
|               32 |         8 |                        28470 |                     6498 |                      128 |                  200 |
|               64 |        16 |                        57961 |                    13626 |                      128 |                  200 |
|               96 |        24 |                        87453 |                    20394 |                      128 |                  200 |
|              128 |        32 |                       116944 |                    27882 |                      128 |                  200 |
|              256 |        64 |                       234909 |                    56394 |                      128 |                  200 |
```

For folks hosting PostgreSQL on Kubernetes. The allocatable memory is almost never on a hard GB boundary. It varies by node/instance type.

We're already paying a 35% to 15% memory overhead penalty, so the idea of just truncating our MB to full-gigabytes to workaround an arbitrary limitation doesn't really serve users well.

**Comment by jmealo** [comment]
I'm happy to remove the non-memory `max` limit increases as well. I just figured for consistency's sake, the removal of arbitrary limits would be an overall improvement for UX and future proofing things.

**Comment by le0pard** [comment]
resolved by https://github.com/le0pard/pgtune/pull/102
