### ISSUE TITLE
effective_io_concurrency not settable on Windows

### ISSUE THREAD

**Issue by EionRobb** [le0pard/pgtune#11]
Specifying 'Windows' as the 'OS Type' still provides 'effective_io_concurrency' as a setting to change in the postgresql.conf file, even though it's not settable on non-Posix systems.  Adding in the recommended setting causes the Postgres service to not start due to conf errors:

```
LOG:  parameter "effective_io_concurrency" cannot be changed
2018-03-02 10:43:16 NZDT FATAL:  configuration file "C:/postgres/postgres9.4/data/postgresql.conf" contains errors
```

**Comment by le0pard** [comment]
@EionRobb thanks, will remove this setting for Windows tomorrow.

**Comment by le0pard** [comment]
@EionRobb fixed by https://github.com/le0pard/pgtune/commit/61af380e13b920dc9b5e29888970fd7952769436
