### ISSUE TITLE
max_wal_senders must be less than max_connections

### ISSUE THREAD

**Issue by mayeulk** [le0pard/pgtune#12]
Running postgresql 10 in Debian 9 (stretch), applying the PgTune parameters with these parameters prevents the server from restarting:
```
# DB Version: 10
# OS Type: linux
# DB Type: mixed
# Total Memory (RAM): 7 GB
# Number of Connections: 8
max_connections = 8
```
The error is:
```
postgres: max_wal_senders must be less than max_connections         
pg_ctl: could not start server
```

Default value in /etc/postgresql/10/main/postgresql.conf is 10:
`#max_wal_senders = 10           # max number of walsender processes:`
Suggested fix (?): if max_connections <10 then set max_wal_senders =max_connections 
(works for me so far; unsure whether this is the best performance-wise).
Cheers,
Mayeul

**Comment by le0pard** [comment]
Hello @mayeulk 

pgtune doesn't provide `max_wal_senders` settings and by default this value is zero (disabled). So looks like it is just inconsistency in your configuration, where you trying to apply pgtune settings.

**Comment by mayeulk** [comment]
OK, as you see best fits.
For the records, from the docs:
[https://www.postgresql.org/docs/10/static/runtime-config-replication.html](https://www.postgresql.org/docs/10/static/runtime-config-replication.html)

> max_wal_senders (integer)
> 
> Specifies the maximum number of concurrent connections from standby servers
> or streaming base backup clients (i.e., the maximum number of simultaneously 
> running WAL sender processes). The default is 10. The value 0 means replication is
> disabled. WAL sender processes count towards the total number of connections, so
> the parameter cannot be set higher than max_connections.

**Comment by le0pard** [comment]
Fixed by https://github.com/le0pard/pgtune/commit/c3df2203df9b6ac7398fcedf4d24eb845f28c939
