### ISSUE TITLE
max wal size doesn't seem correct?

### ISSUE THREAD

**Issue by shongololo** [le0pard/pgtune#13]
Would it please be possible to confirm that the `max_wal_size` settings are correct? I am getting low values for "desktop" scenarios, e.g. as opposed to the default value of 1GB:
e.g.
```
# DB Version: 10
# OS Type: linux
# DB Type: desktop
# Total Memory (RAM): 30 GB
# Number of Connections: 50

max_connections = 50
shared_buffers = 1920MB
effective_cache_size = 7680MB
work_mem = 32MB
maintenance_work_mem = 1920MB
min_wal_size = 100MB
max_wal_size = 100MB
checkpoint_completion_target = 0.5
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
max_worker_processes = 6
max_parallel_workers_per_gather = 3
max_parallel_workers = 6
```

**Comment by le0pard** [comment]
Why do you think `max_wal_size` should be bigger for desktop application? Is this produce some error?

**Comment by shongololo** [comment]
While restoring a database the postgres terminal kept encountering a checkpoint every 3-5s and emitted a warning saying that the max_wal_size should probably be increased. 100MB is 1/10th of the default 1GB hence my question.

**Comment by le0pard** [comment]
For restoring this is clear. What about work load of desktop app?

**Comment by shongololo** [comment]
I've changed it now so I don't know.

**Comment by le0pard** [comment]
Fixed by https://github.com/le0pard/pgtune/commit/2f1f123391c4ffedbb17f9f3419cdb9ca33f8e52
