### ISSUE TITLE
SSD and HDD values swapped

### ISSUE THREAD

**Issue by chappjc** [le0pard/pgtune#16]
The SSD and HDD values for `randomPageCost` and `effectiveIoConcurrency` seem to be swapped.

https://github.com/le0pard/pgtune/blob/a2e8253beaae818bd2777e1c95fe878be83680b3/webpack/selectors/configuration.js#L201-L222

**Comment by le0pard** [comment]
@chappjc thanks, my fault. Now all should be fixed.
