### ISSUE TITLE
Pgtune suggest hundreds for effective_io_concurrenc when using NAS

### ISSUE THREAD

**Issue by aleskinen** [le0pard/pgtune#18]
It seems, that it is bad idea and you get much better efficiency putting small value like 2. Why is that?

**Comment by le0pard** [comment]
> It seems, that it is bad idea and you get much better efficiency putting small value like 2

Where "it seems"?

**Comment by aleskinen** [comment]
I got much better efficiency using HDD settings. Although network mounted volume is slow it gives similar values than with ssd.

**Comment by le0pard** [comment]
> Although network mounted volume is slow

why it slow? Lets check on AWS:

https://aws.amazon.com/ebs/details/

Max IOPS**/Volume:
EBS Provisioned IOPS SSD (io1) - 32000 
EBS General Purpose SSD (gp2) - 10000
Throughput Optimized HDD (st1) - 500 
Cold HDD (sc1) - 250

You can also check numbers on Azure and Google Cloud.

**Comment by aleskinen** [comment]
We have own iscsi disks and at least with them dropping effective_io_concurrency to 2 and raising random_page_cost to 4 gives much better results.

**Comment by le0pard** [comment]
If you NAS slow - select HDD, it will be correct for your case.
