### ISSUE TITLE
algorithms?

### ISSUE THREAD

**Issue by spyhunter99** [le0pard/pgtune#20]
bit of a random question. I just tried out pgtune and it's awesome. Made a large performance improvement for me!

Would it be possible to point me to the algorithms that you use to come up with the config? I'd like to incorporate something similar into my installer software to automate some postgres config settings.

**Comment by le0pard** [comment]
It is based on original https://github.com/gregs1104/pgtune, which is CLI. So you can integrate it to any system.

Calculation inside selectors: https://github.com/le0pard/pgtune/blob/master/webpack/selectors/configuration.js
