### ISSUE TITLE
Setting maintenance_work_mem as 2GB or above causes an error

### ISSUE THREAD

**Issue by KiranRW1** [le0pard/pgtune#21]
After continuous trial and error method, I have found out that Windows has a limit of 2GB for maintenance work memory. Even setting it to 2048MB causes Postgres not to start. So I had to change it to 2047MB. Please modify the application to lower the recommended value for windows configurations.

Possible linked SO Answer,
https://stackoverflow.com/a/33997819

**Comment by le0pard** [comment]
Fixed by https://github.com/le0pard/pgtune/commit/ef7a6c402770f3e97c80e6b8e52cc9b2086a6062
