### ISSUE TITLE
effective_io_concurrency not settable on macOS

### ISSUE THREAD

**Issue by WhitewaterDave** [le0pard/pgtune#22]
This is not an issue, more of a heads up. I'm using PostgreSQL 11 installed using Homebrew on macOS Mojave. One of the parameters that was generated by pgtune at your website is:

`ALTER SYSTEM SET effective_io_concurrency = '200';`

It returned the following error:

`ERROR:  invalid value for parameter "effective_io_concurrency": 200
DETAIL:  effective_io_concurrency must be set to 0 on platforms that lack posix_fadvise()`

I searched for this error prior to posting this. effective_io_concurrency is presumably not supported on macOS.

**Comment by le0pard** [comment]
Thanks @WhitewaterDave Fixed by https://github.com/le0pard/pgtune/commit/19d420626e8d563101b41f68b2d8f6c5f1b97c43
