### ISSUE TITLE
10 connections causes crash

### ISSUE THREAD

**Issue by rigbypc** [le0pard/pgtune#25]
Thanks for keeping this very useful tool going!

I noticed that 
max_connections = 10 
The system wouldn't restart
max_connections = 11 
and above worked.

Thanks.

**Comment by le0pard** [comment]
Hello, @rigbypc . What error do you get?

**Comment by rigbypc** [comment]
It'd didn't throw any error when I did 
service postgresql restart

However, the server was not up. 

psql -l
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

When I increased to 11 connections, everything worked fine.

I'm running postgres 10 on ubuntu desktop

**Comment by le0pard** [comment]
@rigbypc next time read logs:

```
2019-06-03 19:00:26.414 UTC [4308] LOG:  database system is shut down
postgres: max_wal_senders must be less than max_connections
pg_ctl: could not start server
Examine the log output.

root@ubuntu-bionic:~# /etc/init.d/postgresql restart
[ ok ] Restarting postgresql (via systemctl): postgresql.service.
root@ubuntu-bionic:~# su postgres
postgres@ubuntu-bionic:/home/vagrant$ psql
psql (10.8 (Ubuntu 10.8-1.pgdg18.04+1))
Type "help" for help.

postgres=# SHOW max_connections;
 max_connections
-----------------
 10
(1 row)

postgres=# SHOW max_wal_senders;
 max_wal_senders
-----------------
 2
(1 row)
```

**Comment by rigbypc** [comment]
Fair enough, re: logs. 

I'm not db tuning expert, I just pasted in the output from pgtune and the configuration didn't work. 

Perhaps a check that max_wal_senders < max_connections would be nice in pg_tune

**Comment by le0pard** [comment]
@rigbypc But pgtune don't know is you need replication or not. If you no need replication at all, you just set `max_wal_senders` to zero. 

Or maybe you need big amount of a replica databases, but decide set 10 connections. In this case - it is just invalid info for pgtune.

**Comment by rigbypc** [comment]
Sorry, I don't understand. 

![image](https://user-images.githubusercontent.com/1197427/58828070-90e57180-8612-11e9-9a5d-4b1e7d708b4d.png)

On the website you make it >= 10, but this will violate the default setting of 
#max_wal_senders = 10

I don't mind either way, perhaps my datamining research setup is unlikely, now at least, I know.

Thanks

**Comment by le0pard** [comment]
Fixed by https://github.com/le0pard/pgtune/commit/ff9e243a2fe86bf89746a5cbefcfae49d899ed42
