### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by sebastianwebber** [le0pard/pgtune#3]
Hi there,

I wrote a similar tool do suggest tuning parameters and also based on pgtune. 

Take a look at http://pgconfig.org

Do you wanna help me? or perhaps want talk about it?

Thanks

**Comment by le0pard** [comment]
Hello. Yes, it is similar (calculation of params little different for some options), but I don't have explanation for each parameter (idea just to do copy and paste)

> Do you wanna help me?

I am not sure, what do you mean by this.

**Comment by sebastianwebber** [comment]
> I am not sure, what do you mean by this.

If you want, we can work together and make a better tool for facilitate the fine tune of the postgres server.
Until now, our tools only cover the standard values used on the pgtune. we can expand that to another values and review the profiles/environments.

What do you think about it?

**Comment by le0pard** [comment]
This tools cheap and simple - possible to create thousands of its. The main problem - measure current state of this properties for all possible environments (Windows, Linux, SSD disks), measure how will change performance for some queries by changing each variable in PostgreSQL and create correlation for this. This is huge work and need time and resources. Right now I don't have this resources :(
