### ISSUE TITLE
Support Postgres 12

### ISSUE THREAD

**Issue by Friss** [le0pard/pgtune#33]
Basic support will just be adding 12 to the version drop down but we may also need some tweaks to the settings / configuration based on 12. (I don't know if there are any particular changes) 

(Many thanks for creating PGTune!)

**Comment by le0pard** [comment]
@Friss thanks. Fixed by https://github.com/le0pard/pgtune/commit/8e3cebf149c65d3fed8b0ffcbed89b38b93be4e4
