### ISSUE TITLE
Asynchronous Behavior Settings?

### ISSUE THREAD

**Issue by beefo** [le0pard/pgtune#5]
Has there been any thoughts about supporting values for 9.6 Asynchronous Behavior settings?

**Comment by le0pard** [comment]
Hello. What do you mean about "Asynchronous Behavior settings"? `synchronous_commit=off` will not be provided by pgtune, because loosing durability for database.

**Comment by beefo** [comment]
Specifically these settings:
```
# - Asynchronous Behavior -

#effective_io_concurrency = 0		# 1-1000; 0 disables prefetching
#max_worker_processes = 8		# (change requires restart)
#max_parallel_workers_per_gather = 0	# taken from max_worker_processes
#old_snapshot_threshold = -1		# 1min-60d; -1 disables; 0 is immediate
								# (change requires restart)
#backend_flush_after = 0		# 0 disables, default is 0```

As I understand it these are new to posgres 9.6 which added [parallel queries](https://www.postgresql.org/docs/9.6/static/parallel-query.html). 

I was thinking it might be useful to have fields for #cores, #drives raided, type of storage (just spit-balling) to determine default values for these fields.

**Comment by le0pard** [comment]
`effective_io_concurrency` is exists from 9.2, `max_worker_processes` from 9.4 and only `max_parallel_workers_per_gather` from 9.6. 

> I was thinking it might be useful to have fields for #cores, #drives raided, type of storage (just spit-balling) to determine default values for these fields.

It possible, if we have real testing for different hardware - how changing each parameter will influence on performance. After this is possible to make formula to calculate this parameters in pgtune.
