### ISSUE TITLE
Same in Odoo configuration.

### ISSUE THREAD

**Issue by esakarya** [le0pard/pgtune#60]
please create the same in odoo configuration.
limit_memory_hard ?
limit_memory_soft ?
limit_time_cpu ?
limit_time_real ?
workers ?

**Comment by le0pard** [comment]
How exactly odoo related to pgtune and PostgreSQL? @esakarya

**Comment by esakarya** [comment]
i came from here: https://pgtune.leopard.in.ua/

**Comment by le0pard** [comment]
@esakarya it is not answer on my question: how odoo related here?

**Comment by esakarya** [comment]
you did it with given server specs. you do also odoo configs same.

**Comment by le0pard** [comment]
Is odoo some kind PostgreSQL fork? Is it database?

**Comment by esakarya** [comment]
nevermind, misunderstanding:)
