### ISSUE TITLE
parallel worker settings seem wrong in the 2 CPU case

### ISSUE THREAD

**Issue by adamf** [le0pard/pgtune#62]
**Describe the bug**
If you set CPUs=1 for Postgres > 10, you get a `max_parallel_workers_per_gather` of 2. If you set CPU 2 in the same case, the logic at https://github.com/le0pard/pgtune/blob/master/assets/selectors/configuration.js#L269 doesn't kick in, and you end up with a `max_parallel_workers_per_gather` of 2. 

This is because pgtune assumes the parallel defaults for any case where there are less than 2 CPUs. However, the defaults are more aggressive than the pgtune calculations when CPU == 2 (for example).

The question is: should the minimum settings for parallel workers be the default settings? I don't think so. The minimum should probably be what the computation gets us in the parallelSettings selector.

**Comment by adamf** [comment]
This also implies the `work_mem` calculation is incorrect for the 1 CPU case.

**Comment by le0pard** [comment]
Fixed by https://github.com/le0pard/pgtune/commit/41077d501ef36b7c95ccc0483e364ebab82f2230
