### ISSUE TITLE
Support Postgresql 15

### ISSUE THREAD

**Issue by raycke** [le0pard/pgtune#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by le0pard** [comment]
This was done 16 hours ago https://github.com/le0pard/pgtune/commit/41077d501ef36b7c95ccc0483e364ebab82f2230 . So what is the issue? @raycke

**Comment by raycke** [comment]
Hi, @le0pard 

thank you for your reply! I just didn't see the option for version 15 on the official website https://pgtune.leopard.in.ua/, maybe it's just that you haven't officially released it yet?

**Comment by le0pard** [comment]
It is released in the same time by GitHub Actions
![Screenshot_20221014-111907](https://user-images.githubusercontent.com/98444/195798304-af1ef39f-d150-4837-8608-b2ee6330e8f1.png)

**Comment by raycke** [comment]
Oh, turns out I didn't click the "update application" link! Thank you. @le0pard
