### ISSUE TITLE
maintenance work memory is outside of the valid range

### ISSUE THREAD

**Issue by R0Yi** [le0pard/pgtune#69]
https://github.com/le0pard/pgtune/blob/7541f1936a4d95affaf3a90b0f3636669bd7f776/assets/selectors/configuration.js#L145

i've experienced an issue where system has more than 16 gb of ram the script is failing because the memoryvalue is not in the valid range.
according to line  143 i found that : "// Cap maintenance RAM at 2GB on servers with lots of memory"
by checking it further i found that the value that i passed to total memory was still in GB and not converted with the -1MB (line 147)
i fixed the issue by adding "=" operator at line 145.
the new value looks like this: if  (maintenanceWorkMemValue  >=  memoryLimit)  { :

**Comment by le0pard** [comment]
Sorry, not clear about your issue. Where exactly script is failing?

<img width="1260" alt="Screenshot 2023-01-18 at 14 53 53" src="https://user-images.githubusercontent.com/98444/213176923-7549048a-023d-40f2-bf4a-87123b622229.png">

**Comment by le0pard** [comment]
Ok, got it - it is about windows issue. fixed by https://github.com/le0pard/pgtune/commit/637ff4c804629de3591012718b81fc82943109a6
