### ISSUE TITLE
Support settings for parrallel queries in 9.6

### ISSUE THREAD

**Issue by jasonheight** [le0pard/pgtune#7]
Is it possible to add some recommended setings based on number of cores and memory for the parrallell options in 9.6

**Comment by le0pard** [comment]
@jasonheight it is possible, if someone made research with different numbers of cores and memories and create on this working model, which can be used for simple formula in this app. Do you have this data?

**Comment by le0pard** [comment]
@jasonheight ping?

**Comment by jasonheight** [comment]
Yes received. I don't have any experience, I hoped someone may have

Jason

**Comment by MahatmaFatalError** [comment]
One could conduct several test runs with different parallelization configurations and let a mighty ML algorithm find out the optimal formula ;)

Unit then, is it possible to add a optional field "CPU cores" to the form and suggest that max_worker_processes should be set to this value if it's higher than the default 8 (and max_parallel_workers_per_gather accordingly if DB Type is Data Warehouse where few long running queries are expected) ?

It'is clear that this is not optimal, but I think parallelization is a major performance setting which the user should be at least reminded of.

**Comment by le0pard** [comment]
@MahatmaFatalError I understand, just need

> One could conduct several test runs with different parallelization configurations and let a mighty ML algorithm find out the optimal formula ;)

**Comment by le0pard** [comment]
Resolved by https://github.com/le0pard/pgtune/commit/4578969cea77567c7e20ccec4091310f2b1a53c0
