### ISSUE TITLE
pg 15

### ISSUE THREAD

**Issue by bwakkie** [le0pard/pgtune#72]
Is there already a pg 15 settings tuning? Or would 14 work too?

**Comment by le0pard** [comment]
Sorry, I don't get a question. Give me more details

![Screenshot_20230206-130624](https://user-images.githubusercontent.com/98444/216956235-bc1baec0-f24e-48d5-9bd2-3c363c1aa87b.png)

**Comment by bwakkie** [comment]
never mind, I see it now too... maybe it was a caching problem as I used your site like last year also.
