### ISSUE TITLE
Show AWS RDS Config Style

### ISSUE THREAD

**Issue by piraka9011** [le0pard/pgtune#73]
**Is your feature request related to a problem? Please describe.**

I noticed AWS RDS has variables like `DBInstanceClassMemory` and `DBInstanceVCPU` for memory and CPU values respectively ([Official Docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ParamValuesRef.html)).
It would be nice to use the values for some of the config parameters given that the parameters are calculated based on simple formulas.

ex. Setting the `effective_cache_size` to 75% of RAM would be `{DBInstanceClassMemory/98304}`

**Describe the solution you'd like**

Have an option in the postgresql.conf page to "show as AWS RDS values" where the parameters show the formula using RDS variables and not the raw numbers.

**Describe alternatives you've considered**

Simpler option may be to just how the parameter values in their expected units (ex. `shared_buffers` in 8kb units, not in Gb units).

**Additional Context**

Some other examples
* shared_buffers: `{DBInstanceClassMemory/32768}` (25% of memory)
* effective_cache_size: `{DBInstanceClassMemory/98304}` (75% of memory)
* maintenance_work_mem: `LEAST({DBInstanceClassMemory/ 8 / 8}, 262144)` (Or simply /64 instead of /8 /8)
* max_worker_processes: `GREATEST(${DBInstanceVCPU*2},8)`
* max_parallel_workers: `GREATEST(${DBInstanceVCPU/2},8)`
* max_parallel_maintenance_workers: `LEAST(${DBInstanceVCPU/2},4)`

I calculated the DB Instance Percentages using the following formula: `((1024 * 1024 * Percentage / 100) / 8)`
Where:
* `1024 * 1024` converts GB to kB.
* `Percentage/100` is the percentage
* `/8` b/c Postgres memory values works with blocks of 8kB

**Comment by le0pard** [comment]
Hello

> ex. Setting the effective_cache_size to 75% of RAM would be {DBInstanceClassMemory/98304}

I am not sure, why `{DBInstanceClassMemory/98304}` is 75%. Why not `{DBInstanceClassMemory * 0.75}`? Why `98304` this number so universal?

> Simpler option may be to just how the parameter values in their expected units (ex. shared_buffers in 8kb units, not in Gb units).

Based on [official doc](https://www.postgresql.org/docs/current/config-setting.html)

> Valid memory units are B (bytes), kB (kilobytes), MB (megabytes), GB (gigabytes), and TB (terabytes). The multiplier for memory units is 1024, not 1000.

Where exactly was written, that some params have "expected units"?

**Comment by le0pard** [comment]
Closing for now due to inactivity.

**Comment by piraka9011** [comment]
Sorry, this slipped my notifications

> I am not sure, why {DBInstanceClassMemory/98304} is 75%. Why not {DBInstanceClassMemory * 0.75}? Why 98304 this number so universal?

If you take a look at the [official postgres docs](https://www.postgresql.org/docs/14/runtime-config-resource.html), `shared_buffers` and other similar metrics don't use bytes as the individual unit. Instead "it is taken as blocks, that is BLCKSZ bytes, typically 8kB."
You can see this [here](https://postgresqlco.nf/doc/en/param/shared_buffers/) as well in postgresqlco.nf (an easier resource to understand the different Postgres parameters IMO). 

By example, if we want 75% of the DB's memory to be the value of `effective_cache_size`, we use the formula:

```
((1024 * 1024 * 75 / 100) / 8) = 98304
```

The AWS RDS' configuration GUI and API only allows integer values so we can't use our own units when specifying the configuration. This is why I suggested showing the values in the base units Postgres expects (8kb) and not what we specify (mb/gb/etc.)

**Comment by le0pard** [comment]
> If you take a look at the [official postgres docs](https://www.postgresql.org/docs/14/runtime-config-resource.html), shared_buffers and other similar metrics don't use bytes as the individual unit. Instead "it is taken as blocks, that is BLCKSZ bytes, typically 8kB."

Based on official doc, which was pointed earlier PostgreSQL expected unit values in any valid format. Basically we can write `3GB` and `3072MB` and `3145728kB` - this will be applied to configuration in same way. Math inside app use closest number, which can represent result without float. so if in the end we calculated `3145728kB`, which is same as `3GB` - we show in `GB`. For human it more readable.

> By example, if we want 75% of the DB's memory to be the value of effective_cache_size, we use the formula:
> ((1024 * 1024 * 75 / 100) / 8) = 98304

I get where is taken `75 / 100`, but what `((1024 * 1024 ) / 8) = 131072 = 128kB ?` this number? Like I have 64GB instance, why 

```
64GB / 98304 == 75% ?
```

> The AWS RDS' configuration GUI and API only allows integer values so we can't use our own units when specifying the configuration. This is why I suggested showing the values in the base units Postgres expects (8kb) and not what we specify (mb/gb/etc.)

Tool are using not only AWS RDS customers. Other people want config will be readable. 

In the end, if AWS so restrictive, we can just do multiplications. Like by using https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group and https://docs.hashicorp.com/sentinel/imports/units you can set values from pgtune and apply unit conversion
