### ISSUE TITLE
Container options, especially shm-size

### ISSUE THREAD

**Issue by frankhommers** [le0pard/pgtune#75]
I am running postgres in a container but I don't know what to set the container limits exactly to.

I'd like to see that pg_tune also recommends something for the shm-size.

Inspiration:
* https://stackoverflow.com/a/65731661
* https://blog.hasanbul.li/2021/03/03/changing-shm-size-for-postgresql-in-a-docker-container/

This might be out of scope, but I think it would be very beneficial to people running it in a container.
I am also not sure yet on how to calculate the best value for this yet.

**Comment by le0pard** [comment]
Just provide `shm_size` same value as have `shared_buffers`. What issue with such approach?

**Comment by frankhommers** [comment]
Is that the only logic needed? I am really not confident about that. But you might be right.
(Maybe add an auto generated comment behind it then to say so ;-) ).

**Comment by le0pard** [comment]
Tuning PostgreSQL in docker is out of scope for this tool

**Comment by frankhommers** [comment]
Too bad, it would be a nice addition. A lot of people are running it that way.
