### ISSUE TITLE
Does effective_io_concurrency need to be set differently for PostgreSQL 13+?

### ISSUE THREAD

**Issue by jpmckinney** [le0pard/pgtune#79]
https://www.postgresql.org/docs/13/release-13.html#id-1.11.6.16.4

> Change the way non-default [effective_io_concurrency](https://www.postgresql.org/docs/13/runtime-config-resource.html#GUC-EFFECTIVE-IO-CONCURRENCY) values affect concurrency (Thomas Munro)
> 
> Previously, this value was adjusted before setting the number of concurrent requests. The value is now used directly. Conversion of old values to new ones can be done using:
> 
> `SELECT round(sum(OLDVALUE / n::float)) AS newvalue FROM generate_series(1, OLDVALUE) s(n);`

Applying that formula, 2 would become 3, 200 -> 1176, 300 -> 1885 (these can of course be rounded).

But, I don't really understand the change in version 13, so maybe they don't need to be changed?

**Comment by le0pard** [comment]
Thanks @jpmckinney Checking what is any changes needed based on this changelog

**Comment by le0pard** [comment]
Ok, based on https://www.postgresql.org/docs/13/runtime-config-resource.html#GUC-EFFECTIVE-IO-CONCURRENCY - `effective_io_concurrency` the allowed range is 1 to 1000. So we cannot set 

> Applying that formula, 2 would become 3, 200 -> 1176, 300 -> 1885 (these can of course be rounded).

I think author means that the formula should take that into account. That is it

**Comment by jpmckinney** [comment]
Sounds good to me – just wanted to draw attention to the changelog entry in case it had any implications :)
