### ISSUE TITLE
Set pgtune form entries from url params

### ISSUE THREAD

**Issue by n-rodriguez** [le0pard/pgtune#99]
**Is your feature request related to a problem? Please describe.**

It would be nice/handful to set pgtune form entries from url params

**Describe the solution you'd like**

Calling https://pgtune.leopard.in.ua/?db_version=16 should set DB version to 16 and so on

**Describe alternatives you've considered**

None

**Additional context**

None

Thank you!

**Comment by le0pard** [comment]
it is possible to do, but no server here - it may require re-render after parsing query params

**Comment by le0pard** [comment]
Added by https://github.com/le0pard/pgtune/commit/27bf80316c75325012d854a66376de76b785b141

**Comment by n-rodriguez** [comment]
> Added by [27bf803](https://github.com/le0pard/pgtune/commit/27bf80316c75325012d854a66376de76b785b141)

Awesome! Thank you!
